# Generated by Django 3.2.9 on 2022-02-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('educations', models.CharField(blank=True, max_length=200, null=True)),
                ('lichting', models.CharField(blank=True, max_length=200, null=True)),
                ('vertical', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('lid_image', models.ImageField(blank=True, default='images/leden/user-default.png', null=True, upload_to='images/leden/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lichting', 'vertical'],
            },
        ),
    ]
