# Generated by Django 3.2.9 on 2022-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
