# Generated by Django 3.2.9 on 2022-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lid',
            options={'ordering': ['lichting', 'vertical']},
        ),
        migrations.RenameField(
            model_name='lid',
            old_name='anciënniteiten',
            new_name='lichting',
        ),
        migrations.AddField(
            model_name='lid',
            name='vertical',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
