# Generated by Django 4.0.2 on 2022-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lid_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='stand',
            field=models.FloatField(default=0),
        ),
    ]
