# Generated by Django 4.0.2 on 2022-04-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lid_stand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lid',
            name='stand',
        ),
    ]
