# Generated by Django 4.0.2 on 2022-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
