# Generated by Django 4.0.2 on 2022-04-27 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0012_alter_agendaclient_name'),
        ('users', '0002_lid_initials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decla',
            fields=[
                ('content', models.TextField(max_length=50)),
                ('total', models.FloatField()),
                ('senate_year', models.IntegerField(default=32)),
                ('receipt', models.ImageField(upload_to='declas/')),
                ('reunist', models.IntegerField()),
                ('kmters', models.IntegerField()),
                ('verwerkt', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lid')),
                ('present', models.ManyToManyField(blank=True, related_name='present_leden', to='users.Lid')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
    ]
