# Generated by Django 4.0.2 on 2022-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decla',
            name='kmters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decla',
            name='reunist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decla',
            name='verwerkt',
            field=models.BooleanField(default=False),
        ),
    ]
