# Generated by Django 4.0.2 on 2022-05-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bier_boekstuk_decla_content_ficus_decla_boekstuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='initial_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='decla',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='declas/'),
        ),
    ]
