# Generated by Django 4.0.2 on 2022-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lid_active_alter_lid_initials'),
        ('finance', '0003_stand_initial_amount_alter_decla_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decla',
            name='present',
            field=models.ManyToManyField(related_name='present_leden', to='users.Lid'),
        ),
    ]
