# Generated by Django 4.1a1 on 2022-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_decla_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boekstuk',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
