# Generated by Django 3.2.9 on 2022-02-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20220207_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('token_uri', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('scopes', models.CharField(blank=True, max_length=2000, null=True)),
                ('expiry', models.CharField(blank=True, max_length=200, null=True)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lid')),
            ],
        ),
    ]
