# Generated by Django 3.2.9 on 2022-02-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recuring', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('kokers', models.CharField(blank=True, max_length=50, null=True)),
                ('kartrekkers', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('bijzonderheden', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('token_uri', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('scopes', models.CharField(blank=True, max_length=2000, null=True)),
                ('expiry', models.CharField(blank=True, max_length=200, null=True)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lid')),
            ],
        ),
    ]
