# Generated by Django 4.0.2 on 2022-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(choices=[('Activiteit', 'Activiteit'), ('Borrel', 'Borrel'), ('Clubactiviteit', 'Clubactiviteit'), ('Wedstrijd', 'Wedstrijd'), ('Dispuutsactiviteit', 'Dispuutsactiviteit'), ('Dispuutsverjaardag', 'Dispuutsverjaardag')], max_length=50),
        ),
    ]
