# Generated by Django 3.2.9 on 2022-02-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.event')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lid')),
            ],
        ),
    ]
