# Generated by Django 4.0.2 on 2022-03-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lid_initials'),
        ('agenda', '0003_event_end_date_event_start_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-start_time', '-end_date']},
        ),
        migrations.AlterField(
            model_name='nievent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dsani_ev', to='agenda.event'),
        ),
        migrations.AlterField(
            model_name='nievent',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lid', unique=True),
        ),
    ]
