# Generated by Django 3.2.9 on 2022-02-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='kartrekkers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='kokers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
