# Generated by Django 4.0.2 on 2022-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agendaclient_name_alter_nievent_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bijzonderheden',
            field=models.CharField(choices=[('Op Afmelding', 'Op Afmelding'), ('Op Aanmelding', 'Op Aanmelding'), (' ', ' ')], default='Op Afmelding', max_length=50),
        ),
    ]
