# Generated by Django 3.2.9 on 2022-02-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20220210_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
