# Generated by Django 4.0.2 on 2022-03-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_nievent_event_alter_nievent_lid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time', '-end_date']},
        ),
    ]
