# Generated by Django 4.0.2 on 2022-03-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nievent',
            options={'ordering': ['lid']},
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
