# Generated by Django 4.0.2 on 2022-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lid_active_alter_lid_initials'),
        ('agenda', '0006_event_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kokers',
        ),
        migrations.AddField(
            model_name='event',
            name='kokers',
            field=models.ManyToManyField(blank=True, related_name='kookshift', to='users.Lid'),
        ),
    ]
