# Generated by Django 4.0.2 on 2022-06-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_event_kokers_event_kokers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nievent',
            options={'ordering': ['event']},
        ),
    ]
