# Generated by Django 4.0.2 on 2022-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_event_google_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaclient',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='lid',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='token',
        ),
        migrations.RemoveField(
            model_name='agendaclient',
            name='token_uri',
        ),
        migrations.AddField(
            model_name='agendaclient',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
