# Generated by Django 4.0.2 on 2022-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_agendaclient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaclient',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
