# Generated by Django 4.0.2 on 2022-05-01 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('senate_year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('show', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lid')),
            ],
            options={
                'ordering': ['senate_year'],
            },
        ),
    ]
