# Generated by Django 4.0.2 on 2022-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='senate_year',
            field=models.IntegerField(verbose_name=32),
        ),
    ]
