# Generated by Django 3.2.9 on 2022-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_links_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='start_date',
            field=models.DateField(),
        ),
    ]
